name:                promigrate
version:             0.1.0.0
github:              "Prosumma/hs-promigrate"
license:             BSD-3-Clause
author:              "Gregory Higley / Prosumma Inc."
maintainer:          "greg@prosumma.com"
copyright:           "2023 Gregory Higley / Prosumma Inc."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/promigrate#readme>

dependencies:
- base >= 4.7 && < 5
- rio

default-extensions:
- NoImplicitPrelude

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  promigrate-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - promigrate

tests:
  promigrate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - promigrate
